### ISSUE TITLE
When trying to click on an object that isn't in the view port (but is in the xml) mac2 driver crashes

### ISSUE THREAD

**Issue by Jiurong-Yang** [appium/appium-mac2-driver#71] opened 2021-04-08 22:31 UTC
When trying to click on an element that's not visible, although can be found because it is in the xml. The driver crashes

Appium version: 1.20.2

2021-04-08 15:26:19:749 - [debug] [W3C (6c85cf50)] Calling AppiumDriver.findElement() with args: ["xpath","//*[@title='HP Mobile Printing']","6c85cf50-950d-43d9-9fb5-c070bf420282"]
2021-04-08 15:26:19:749 - [debug] [BaseDriver] Valid locator strategies for this request: id, name, accessibility id, xpath, class name, -ios predicate string, predicate string, -ios class chain, class chain
2021-04-08 15:26:19:749 - [debug] [WD Proxy] Matched '/element' to command name 'findElement'
2021-04-08 15:26:19:749 - [debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:10100/session/DA379BDF-716B-42A0-A7D7-AB6532E1883D/element] with body: {"using":"xpath","value":"//*[@title='HP Mobile Printing']"}
2021-04-08 15:26:20:337 - [debug] [WD Proxy] Got response with status 200: {"value":{"ELEMENT":"A92E5490-5406-411E-8505-D7085055F6F3","element-6066-11e4-a52e-4f735466cecf":"A92E5490-5406-411E-8505-D7085055F6F3"},"sessionId":"DA379BDF-716B-42A0-A7D7-AB6532E1883D"}
2021-04-08 15:26:20:338 - [debug] [W3C (6c85cf50)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"A92E5490-5406-411E-8505-D7085055F6F3","ELEMENT":"A92E5490-5406-411E-8505-D7085055F6F3"}
2021-04-08 15:26:20:338 - [HTTP] <-- POST /wd/hub/session/6c85cf50-950d-43d9-9fb5-c070bf420282/element 200 590 ms - 137
2021-04-08 15:26:20:338 - [HTTP] 
2021-04-08 15:26:20:344 - [HTTP] --> POST /wd/hub/session/6c85cf50-950d-43d9-9fb5-c070bf420282/element/A92E5490-5406-411E-8505-D7085055F6F3/click
2021-04-08 15:26:20:344 - [HTTP] {"id":"A92E5490-5406-411E-8505-D7085055F6F3"}
2021-04-08 15:26:20:345 - [W3C (6c85cf50)] Driver proxy active, passing request on via HTTP proxy
2021-04-08 15:26:20:346 - [debug] [WD Proxy] Matched '/wd/hub/session/6c85cf50-950d-43d9-9fb5-c070bf420282/element/A92E5490-5406-411E-8505-D7085055F6F3/click' to command name 'click'
2021-04-08 15:26:20:346 - [debug] [WD Proxy] Proxying [POST /wd/hub/session/6c85cf50-950d-43d9-9fb5-c070bf420282/element/A92E5490-5406-411E-8505-D7085055F6F3/click] to [POST http://127.0.0.1:10100/session/DA379BDF-716B-42A0-A7D7-AB6532E1883D/element/A92E5490-5406-411E-8505-D7085055F6F3/click] with body: {"id":"A92E5490-5406-411E-8505-D7085055F6F3"}
2021-04-08 15:26:21:834 - [debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"DA379BDF-716B-42A0-A7D7-AB6532E1883D"}
2021-04-08 15:26:21:835 - [WD Proxy] Replacing sessionId DA379BDF-716B-42A0-A7D7-AB6532E1883D with 6c85cf50-950d-43d9-9fb5-c070bf420282
2021-04-08 15:26:21:835 - [HTTP] <-- POST /wd/hub/session/6c85cf50-950d-43d9-9fb5-c070bf420282/element/A92E5490-5406-411E-8505-D7085055F6F3/click 200 1491 ms - 65
2021-04-08 15:26:21:835 - [HTTP] 
2021-04-08 15:26:22:359 - [WebDriverAgentMac] Mac2Driver host process has exited with code 65, signal null

**Comment by mykola-mokhnach** [comment] 2021-04-09 04:49
Please attach the log with xcodebuild logging enabled

**Comment by Jiurong-Yang** [comment] 2021-04-13 22:00
https://gist.github.com/Jiurong-Yang/0091fc232860ace9c4a923b829a87a17

This is the entire log from starting session to clicking on the not visible object to WDA crashing. With xcodebuild logging turned on. Also double checked that xcode helper have accessibility access.

**Comment by Jiurong-Yang** [comment] 2021-04-13 22:19
Additional info for helping you guys debug. When I do this I actually see the mouse moving, it goes to a few places and it end up on the top left corner of the screen and clicks. So it clicks the apple icon and brings up the system menu. Also this element that I am using is in a XCUIElementTypeWebView container. Not sure if that makes a difference. But either way it shouldn't just crash.

**Comment by Jiurong-Yang** [comment] 2021-04-13 23:36
https://gist.github.com/Jiurong-Yang/3ed1320ad6f76c340a8c2962eec19d4e
This is the page source, as you can see the element i'm trying to click on is in a scroll view. And also inside a webview. Probably the root cause of the crashing issue.

**Comment by mykola-mokhnach** [comment] 2021-04-14 05:47
This is a duplicate of https://github.com/appium/appium-mac2-driver/issues/70

**Closed by mykola-mokhnach** 2021-04-14 05:47 UTC
