### ISSUE TITLE
Finding elements on Big Sur using find_elements is failing!

### ISSUE THREAD

**Issue by psivaa** [appium/appium-mac2-driver#106] opened 2021-12-31 17:32 UTC
Hello,
This could be a question rather than an issue but I need some help with Appium For Mac. 

Basically, I have a test application for Mac (XCUIElementTypeApplication type) and am trying to automate some tests for it using AppiumForMac

This is what I have done so far:

1. Got Appium Server Gui working that uses appium-mac2-driver
2. I am able to obtain the absolute Xpath for the elements on the app using Appium inspector. 
3. Have built AppiumForMac.app using Xcode for the Mac versions that I'm using (Big Sur x86 and Big Sur M1)
4. Now, using those absolute paths (*also* with some tweaks) and using the build AppliumForMac.app, I was trying to retrieve the elements (**find_element_by_xpath** and **find_element**()) etc but I keep getting "_An element could not be located on the page using the given search parameters._" error. 

Could you spot what I'm missing here please? The following is the bareminimum test script. 

```
#!/usr/bin/env python
import time

from selenium import webdriver

# some of these could be syntactically wrong
paths = [
    "/XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]",
    "/XCUIElementTypeApplication/XCUIElementTypeMenuBar/XCUIElementTypeMenuBarItem[6]",
    "/XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeButton[1]",
    "/XCUIElementTypeApplication/XCUIElementTypeWindow/XCUIElementTypeButton[1]",
    "/XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeStaticText[1]"
    ]

defaultLoopDelay_sec = 1.00
defaultCommandDelay_sec = 0.100
defaultImplicitTimeout_sec = 3.000
defaultMouseSpeed = 30
defaultScreenShotOnError = False
defaultGlobalDiagnosticsDirectory = '~/Desktop/'
defaultCookies = [
    {'name': 'loop_delay', 'value': 1.00},
    {'name': 'command_delay', 'value':0.100 },
    {'name': 'implicit_timeout', 'value': 3.000},
    {'name': 'mouse_speed', 'value': 30},
    {'name': 'screen_shot_on_error', 'value': False},
    {'name': 'global_diagnostics_directory', 'value': '~/Desktop/'}
]
desiredCapabilities = {'platform': 'Mac', 'cookies': defaultCookies}
driver = webdriver.Remote( command_executor='http://localhost:4622/wd/hub', desired_capabilities=desiredCapabilities)
driver.get("/Applications/MyTestApp.app")

time.sleep(5)

for xpath in windowPaths:
    try:
        print('Finding some elements for' + xpath)
        element = driver.find_element_by_xpath(xpath)
        print('YES: ' + xpath)
    except Exception as exc:
        print('NO: ' + xpath)
        print(exc.msg)
        print()

time.sleep(2)
driver.quit()
```

**Comment by KazuCocoa** [comment] 2022-01-01 01:35
What's the result of https://appium.io/docs/en/commands/session/source/?

**Comment by psivaa** [comment] 2022-01-01 10:51
Thanks for the reply. 

```page_source``` returns empty ```<?xml version="1.0"?>``` when I get the page_source after about 5 s of opening the app. The app opens without any issues with ```driver.get("/Applications/MyTestApp.app")```

**Comment by KazuCocoa** [comment] 2022-01-02 01:35
Wait, I'm confused.

> This could be a question rather than an issue but I need some help with Appium For Mac.

Are you asking deprecated https://github.com/appium/appium-mac-driver and https://github.com/appium/appium-for-mac rather than this mac2 driver?
Then, the mac driver cannot work with `XCUIElement` stuff since the driver is not via XCTest framework.

**Comment by psivaa** [comment] 2022-01-02 11:05
Sorry, I wasn't aware that 'AppiumForMac' is deprecated. The script was modified from one of those in the example scripts in https://github.com/appium/appium-for-mac. FWIW, I had in fact tried ```Appium Server GUI``` to run this script **without** ```'autmationName': 'mac2'```, but the script kept spawning AppiumForMac. 

When I add the above capability, 'AppiumForMac' is not being spawned but the Server GUI fails to open up the app with the following stacktrace and error code -50:
```
driver = webdriver.Remote( command_executor='http://localhost:4622/wd/hub', desired_capabilities=desiredCapabilities)
Traceback (most recent call last):
  File "/Users/psivaa/appium-for-mac/examples/others/scs.py", line 30, in <module>
    driver.get("/Applications/MyTestApp.app")
  File "/Users/psivaa/appium-for-mac/examples/others/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 436, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/psivaa/appium-for-mac/examples/others/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/Users/psivaa/appium-for-mac/examples/others/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: '/Applications/MyTestApp.app' cannot be opened
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: '/Applications/MyTestApp.app' cannot be opened
    at errorFromW3CJsonCode (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
    at ProxyRequestError.getActualError (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
    at asyncHandler (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:373:25)
```
```appium-mac2-driver``` is present under ```/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules``` though

Could I know what I'm missing here?

**Comment by KazuCocoa** [comment] 2022-01-02 22:06
Have you set up the mac2 env as https://github.com/appium/appium-mac2-driver#requirements ?

**Comment by psivaa** [comment] 2022-01-03 08:29
Yes, 
1)Big Sur M1 (and x86)
2) Xcode Version 13.2.1 (13C100)
3) ![image](https://user-images.githubusercontent.com/19263913/147911121-f27e9e6d-9c5b-4549-ac37-8f86d79b54e9.png)

**Comment by KazuCocoa** [comment] 2022-01-03 08:54
Then, probably the system log may help to check the cause.
As this driver, the end to launch an app is https://developer.apple.com/documentation/xctest/xcuiapplication/1500467-launch by Apple. So possibly only Apple can fix it.

**Comment by psivaa** [comment] 2022-01-04 10:49
/var/log/system.log only contains the following during the server start (on the x86 machine):
```
Jan  4 09:39:33 psivaa com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.io.appium.desktop.130492029.130492330(504)> [72333]
Jan  4 09:39:37 psivaa Appium Server GUI Helper (GPU)[34824]: getattrlist failed for /System/Library/Extensions/AppleIntelKBLGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsGLDriver: #2: No such file or directory
Jan  4 09:39:37 psivaa Appium Server GUI Helper (GPU)[34824]: getattrlist failed for /Library/GPUBundles/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/ATIRadeonX4000SCLib.dylib: #2: No such file or directory
Jan  4 09:39:37 psivaa Appium Server GUI Helper (GPU)[34824]: getattrlist failed for /System/Library/Extensions/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/ATIRadeonX4000SCLib.dylib: #2: No such file or directory
Jan  4 09:39:37 psivaa Appium Server GUI Helper (GPU)[34824]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
```
But nothing is logged when the particular error occurs, (i.e. when the test script is run). 

The same error is seen on both Big Sur x86 and Big Sur M1.

**Comment by KazuCocoa** [comment] 2022-01-04 18:25
Then, what about get device log via Console.app?

**Comment by psivaa** [comment] 2022-01-31 15:49
Sorry for the delay in responding.  I see the following in Console.app when I try to run the script while the app name was applied in the console app search box. When 'Appium' was used to filter the messages, there's no entry made when the script fails. 

```
(error	15:34:13.867300+0000	CoreServicesUIAgent	LAUNCH: Launch failed in CSUI with error Error Domain=NSOSStatusErrorDomain Code=-50 "paramErr: error in user parameter list" UserInfo={_LSLine=3844, LSErrorDict={
    Action = GURL;
    ErrorCode =  #"-50";
    FullPaths =     (
        "/Applications/MyTestApp.app"
    );
    URLs =     (
        "/Applications/MyTestApp.app"
    );
}, _LSFunction=_LSOpenStuffCallLocal}
error	15:34:13.867425+0000	CoreServicesUIAgent	handle LS launch error: {\n    Action = GURL;\n    ErrorCode = "-50";\n    FullPaths =     (\n        "/Applications/MyTestApp.app"\n    );\n    URLs =     (\n        "/Applications/MyTestApp.app"\n    );\n}
```

**Comment by KazuCocoa** [comment] 2022-02-03 09:08
Could be similar to https://developer.apple.com/forums/thread/686838 ?


Close this issue since the original issue was by deprecated module.
It is np to continue commenting on this thread though

**Closed by KazuCocoa** 2022-02-03 09:08 UTC
Labels: needs info
